"""
generate_figures.py
-------------------
Generates the four figures for the FlowPMO academic paper (SBES/CBSoft 2024).

Usage:
    python paper/generate_figures.py

Requires: numpy, pandas, matplotlib
Input:    paper/data/developers_q3_2024.csv  (generated by generate_synthetic_data.py)
Output:   paper/figures/fig1_radar.{pdf,png}
          paper/figures/fig2_scatter.{pdf,png}
          paper/figures/fig3_histogram.{pdf,png}
          paper/figures/fig4_role_bars.{pdf,png}
"""

import os
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable

# ── reproducibility ──────────────────────────────────────────────────────────
np.random.seed(42)

# ── style ─────────────────────────────────────────────────────────────────────
for style_name in ("seaborn-v0_8-whitegrid", "seaborn-whitegrid"):
    try:
        plt.style.use(style_name)
        break
    except OSError:
        continue

# ── paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(SCRIPT_DIR, "data", "developers_q3_2024.csv")
FIGURES_DIR = os.path.join(SCRIPT_DIR, "figures")
os.makedirs(FIGURES_DIR, exist_ok=True)


def save_figure(fig, name):
    """Save figure as both PDF and PNG (300 dpi) in the figures directory."""
    pdf_path = os.path.join(FIGURES_DIR, f"{name}.pdf")
    png_path = os.path.join(FIGURES_DIR, f"{name}.png")
    fig.savefig(pdf_path, bbox_inches="tight")
    fig.savefig(png_path, bbox_inches="tight", dpi=300)
    plt.close(fig)


# ── load data ─────────────────────────────────────────────────────────────────
df = pd.read_csv(DATA_PATH)

# Normalised dimension columns expected in CSV
DIM_COLS = [
    "_rb_entrega",
    "_rb_flow",
    "_rb_revisao",
    "_rb_conformance",
    "_rb_anti_rework",
]
DIM_LABELS = ["Entrega", "Flow\nEfficiency", "Revisão", "Conformance", "Anti-\nRetrabalho"]

# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 1 — Radar Chart (Top 10 by score_benchmark)
# ─────────────────────────────────────────────────────────────────────────────

def make_radar(df):
    top10 = df.nlargest(10, "score_benchmark").reset_index(drop=True)

    n_dim = len(DIM_LABELS)
    angles = [i / n_dim * 2 * math.pi for i in range(n_dim)]
    angles += angles[:1]  # close the polygon

    fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(polar=True))
    colors = plt.cm.tab10(np.linspace(0, 1, 10))

    for idx, row in top10.iterrows():
        values = [row[col] for col in DIM_COLS]
        values += values[:1]

        short_name = row["developer_name"] if "developer_name" in row else f"Dev {idx+1}"
        ax.plot(angles, values, color=colors[idx], linewidth=1.5, label=short_name)
        ax.fill(angles, values, color=colors[idx], alpha=0.3)

    # Reference traces
    ref_min = [75] * n_dim + [75]
    ref_exc = [100] * n_dim + [100]
    ax.plot(angles, ref_min, "--", color="orange", linewidth=1.5,
            label="Mín. Esperado (75)")
    ax.plot(angles, ref_exc, ":", color="green", linewidth=1.5,
            label="Excelência (100)")

    # Axis labels
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(DIM_LABELS, fontsize=11)
    ax.set_ylim(0, 110)
    ax.set_yticks([25, 50, 75, 100])
    ax.set_yticklabels(["25", "50", "75", "100"], fontsize=8, color="grey")

    ax.set_title("Perfil Multidimensional — Top 10 por Score Benchmark",
                 fontsize=13, fontweight="bold", pad=20)
    ax.legend(loc="upper right", bbox_to_anchor=(1.30, 1.10), fontsize=8,
              framealpha=0.8)

    plt.tight_layout()
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 2 — Scatter Plot (Flow Efficiency × Conformance Quality)
# ─────────────────────────────────────────────────────────────────────────────

def make_scatter(df):
    fig, ax = plt.subplots(figsize=(10, 7))

    x = df["flow_efficiency_pct"]
    y = df["conformance_quality_pct"]
    c = df["rework_rate_pct"]
    s = df["wip_residual"] * 40 + 30

    norm = Normalize(vmin=c.min(), vmax=c.max())
    cmap = plt.cm.get_cmap("RdYlGn_r")
    scatter = ax.scatter(x, y, c=c, s=s, cmap=cmap, norm=norm,
                         edgecolors="white", linewidths=0.5, alpha=0.85)

    # Benchmark lines
    ax.axvline(x=80, linestyle="--", color="steelblue", linewidth=1.2,
               label="FE benchmark (80%)")
    ax.axhline(y=75, linestyle="--", color="darkorange", linewidth=1.2,
               label="Conformance benchmark (75%)")

    # Quadrant annotations
    x_min, x_max = ax.get_xlim()
    y_min, y_max = ax.get_ylim()
    ax.text(81, y_max * 0.97, "Alta FE / Alta Conf", fontsize=8,
            color="grey", ha="left", va="top")
    ax.text(x_min + 1, y_max * 0.97, "Baixa FE / Alta Conf", fontsize=8,
            color="grey", ha="left", va="top")
    ax.text(81, y_min + 1, "Alta FE / Baixa Conf", fontsize=8,
            color="grey", ha="left", va="bottom")
    ax.text(x_min + 1, y_min + 1, "Baixa FE / Baixa Conf", fontsize=8,
            color="grey", ha="left", va="bottom")

    cb = fig.colorbar(scatter, ax=ax, pad=0.02)
    cb.set_label("Rework Rate (%)", fontsize=10)

    ax.set_xlabel("Flow Efficiency (%)", fontsize=11)
    ax.set_ylabel("Conformance Quality (%)", fontsize=11)
    ax.set_title(
        "Flow Efficiency × Conformance Quality\n"
        "(cor = Rework Rate, tamanho = WIP Residual)",
        fontsize=12, fontweight="bold"
    )
    ax.legend(fontsize=9, loc="lower right")
    plt.tight_layout()
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 3 — Score Benchmark Histogram
# ─────────────────────────────────────────────────────────────────────────────

def make_histogram(df):
    fig, ax = plt.subplots(figsize=(10, 7))

    bins = np.arange(50, 106, 10)
    scores = df["score_benchmark"].values
    median_val = np.median(scores)

    # Draw histogram manually to colour each bar
    n, bin_edges = np.histogram(scores, bins=bins)
    for i, count in enumerate(n):
        lo = bin_edges[i]
        hi = bin_edges[i + 1]
        mid = (lo + hi) / 2
        if mid < 75:
            color = "#e74c3c"
        elif mid < 85:
            color = "#f39c12"
        else:
            color = "#27ae60"
        ax.bar(lo, count, width=hi - lo, align="edge",
               color=color, edgecolor="white", linewidth=0.8)

    # Reference lines
    ax.axvline(x=75, linestyle="--", color="darkorange", linewidth=1.5,
               label="Mínimo Esperado (75)")
    ax.axvline(x=100, linestyle="--", color="green", linewidth=1.5,
               label="Excelência (100)")
    ax.axvline(x=median_val, linestyle="-", color="#2980b9", linewidth=2.0,
               label=f"Mediana = {median_val:.1f}")

    ax.set_xlabel("Score Benchmark", fontsize=11)
    ax.set_ylabel("Nº de Desenvolvedores", fontsize=11)
    ax.set_title(f"Distribuição do Score Benchmark (n=28, Q3 2024)", fontsize=12,
                 fontweight="bold")
    ax.legend(fontsize=9)
    plt.tight_layout()
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 4 — Role Comparison Bar Chart
# ─────────────────────────────────────────────────────────────────────────────

def make_role_bars():
    fig, ax = plt.subplots(figsize=(10, 7))

    dim_labels = ["Entrega", "Flow\nEfficiency", "Revisão", "Conformance", "Anti-\nRetrabalho"]
    dev_values = [80.8, 86.9, 93.9, 89.4, 96.8]
    tl_values  = [47.1, 76.8, 97.7, 85.7, 97.3]

    x = np.arange(len(dim_labels))
    width = 0.35

    bars_dev = ax.bar(x - width / 2, dev_values, width, label="Dev",
                      color="#2980b9", edgecolor="white", linewidth=0.8)
    bars_tl  = ax.bar(x + width / 2, tl_values,  width, label="Tech Lead",
                      color="#e67e22", edgecolor="white", linewidth=0.8)

    # Value annotations
    for bar in bars_dev:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.8,
                f"{bar.get_height():.1f}",
                ha="center", va="bottom", fontsize=9, color="#2980b9", fontweight="bold")
    for bar in bars_tl:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.8,
                f"{bar.get_height():.1f}",
                ha="center", va="bottom", fontsize=9, color="#e67e22", fontweight="bold")

    # Reference lines
    ax.axhline(y=75,  linestyle="--", color="darkorange", linewidth=1.2,
               label="Mínimo Esperado (75)")
    ax.axhline(y=100, linestyle="--", color="green", linewidth=1.2,
               label="Excelência (100)")

    ax.set_xticks(x)
    ax.set_xticklabels(dim_labels, fontsize=11)
    ax.set_ylim(0, 110)
    ax.set_ylabel("Score Normalizado (0–100)", fontsize=11)
    ax.set_title("Perfil Normalizado por Papel — Tech Lead vs Dev",
                 fontsize=12, fontweight="bold")
    ax.legend(fontsize=10)
    plt.tight_layout()
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"Reading data from: {DATA_PATH}")

    fig1 = make_radar(df)
    save_figure(fig1, "fig1_radar")
    print("  [1/4] fig1_radar saved.")

    fig2 = make_scatter(df)
    save_figure(fig2, "fig2_scatter")
    print("  [2/4] fig2_scatter saved.")

    fig3 = make_histogram(df)
    save_figure(fig3, "fig3_histogram")
    print("  [3/4] fig3_histogram saved.")

    fig4 = make_role_bars()
    save_figure(fig4, "fig4_role_bars")
    print("  [4/4] fig4_role_bars saved.")

    print(
        "\nFigures generated: fig1_radar, fig2_scatter, fig3_histogram, fig4_role_bars"
        " — saved as PDF and PNG in paper/figures/"
    )
